``` plantuml
@startuml configuraciones

skinparam actor {
    BorderColor blue
    BackgroundColor LightBlue
    FontSize 14
    FontStyle bold
    FontColor DarkBlue
} 
skinparam usecase {
    BorderThickness 5
    BorderColor LightSteelBlue
    BackgroundColor WhiteSmoke
    Shadowing false
    FontName courier
    ArrowColor DeepSkyBlue
    LifeLineBorderColor blue
    StereotypeFontColor Red
}
skinparam default {
    FontName courier
    FontSize 14  
}
skinparam rectangle{
    BorderThickness 4
    BorderColor DarkBlue
}
skinparam package {
    StereotypeFontColor Red
}
skinparam note {
    BackgroundColor DarkCyan
    BorderColor Black
    BorderThickness 4
}

'skinparam SwimlaneBorderThickness 3
'skinparam SwimlaneTitleFontSize 12
'skinparam SwimlaneTitleBackgroundColor LightCyan
'skinparam SwimlaneBorderColor DarkBlue
'skinparam SwimlaneTitleFontColor Black
'skinparam SwimlaneTitleFontStyle bold
skinparam Swinlane {
    BorderThickness 3
    TitleFontSize 12
    BorderColor DarkBlue
    TitleFontColor Black
    TitleFontStyle bold
}
skinparam SwimlaneTitleBackgroundColor DeepSkyBlue
skinparam Activity {
    BackgroundColor DeepSkyBlue
    BorderThickness 3
    BorderColor LightSteelBlue
    DiamondBackgroundColor Red
    DiamondFontStyle italic
    DiamondBorderColor DarkTurquoise
    DiamondFontColor FloralWhite
    StartColor DarkBlue
    EndColor DarkBlue
}
skinparam ArrowHeadColor DarkBlue
skinparam linetype polyline
skinparam linetype ortho
hide empty members
skinparam Handwritten false
'allowmixing
@enduml
```  