``` plantuml
@startuml configuraciones

skinparam actor {
    BorderColor blue
    BackgroundColor LightBlue
    FontSize 14
    FontStyle bold
    FontColor DarkBlue
} 
skinparam usecase {
    BorderThickness 5
    BorderColor LightSteelBlue
    BackgroundColor WhiteSmoke
    Shadowing false
    FontName courier
    LifeLineBorderColor blue
    StereotypeFontColor Red
}
skinparam default {
    FontName courier
    FontSize 14  
}
skinparam rectangle{
    BorderThickness 4
    BorderColor DarkBlue
}
skinparam package {
    StereotypeFontColor Red
}
skinparam note {
    BackgroundColor DarkCyan
    BorderColor Black
    BorderThickness 4
}

skinparam Swinlane {
    BorderThickness 3
    TitleFontSize 12
    BorderColor DarkBlue
    TitleFontColor Black
    TitleFontStyle bold
}
skinparam SwimlaneTitleBackgroundColor DeepSkyBlue
skinparam Activity {
    BackgroundColor DeepSkyBlue
    BorderThickness 3
    BorderColor LightSteelBlue
    DiamondBackgroundColor Red
    DiamondFontStyle italic
    DiamondBorderColor DarkTurquoise
    DiamondFontColor FloralWhite
    StartColor DarkBlue
    EndColor DarkBlue
}
skinparam ClassBackgroundColor LightCyan
skinparam ClassFontColor Black
skinparam ClassAttributeFontName courier
skinparam ClassHeaderBackgroundColor DodgerBlue
skinparam ClassBorderColor LightSteelBlue
skinparam ClassBorderThickness 3
skinparam ClassFontName courier
skinparam ClassStereotypeFontColor DarkBlue
skinparam ClassStereotypeFontName courier
skinparam ClassStereotypeFontSize 15
skinparam StereotypeCBorderColor Blue
skinparam StereotypeCBackgroundColor White
skinparam CircledCharacterRadius 15
skinparam CircledCharacterFontName symbol
skinparam CircledCharacterFontSize 24
skinparam CircledCharacterFontStyle bold
skinparam PackageBackgroundColor SteelBlue
skinparam PackageBorderColor LightSteelBlue
skinparam PackageFontName courier
skinparam PackageBorderThickness 4
skinparam PackageStereotypeFontColor DarkBlue
skinparam PackageFontSize 16

'flechas y lineas de conexion
skinparam ArrowColor Black
skinparam ArrowThickness 3

skinparam linetype polyline
skinparam linetype ortho
hide empty members
skinparam Handwritten false
'allowmixing
@enduml
```  