```
@startuml actividad buscar producto
title
    diagrama de actividad 
    buscarMedicamento
    **sistema de Farmacia**
end title
header
    usuarios no registrados
end header
!include https://raw.githubusercontent.com/vonbeitthia/FarmaciaUML/main/skin/blue.plantuml

|A10UsuarioAnonimo|
start
|Sistema|
:buscarMedicamento;
note right
    <<TODO list>>
    #logSistema
    #frontend/backend
    #VerificarIdentidad
    #HistorialBusqueda
end note
if (encontrado) then (verdadero)
    |A10UsuarioAnonimo|
    :informacionMedicamento; 
    note right
        frontend
    end note
    stop
else (falso)
    |Sistema|
    stop
endif


@enduml
```