```
@startuml actividad buscar producto
title
    diagrama de actividad 
    buscarMedicamento
    **sistema de Farmacia**
end title
header
    usuarios no registrados
end header
!include https://raw.githubusercontent.com/vonbeitthia/FarmaciaUML/main/skin/blue.plantuml

|A10UsuarioAnonimo|
start
|Sistema|
:buscarMedicamento;
if (encontrado) then (verdadero)
    |A10UsuarioAnonimo|
    :informacionMedicamento;
    stop
else (falso)
    |Sistema|
    stop
endif
skinparam Activity {
    BackgroundColor LightGray-Cyan
    BorderThickness 3
    BorderColor Red
    DiamondBackgroundColor Beige
}

@enduml
```