```plantuml
@startuml analisis de clases
title
    Analisis de clases 
    **sistema de Farmacia**
end title
header
    Ordenado por espacios de nombre
end header
!include https://raw.githubusercontent.com/vonbeitthia/FarmaciaUML/main/skin/blue.plantuml
namespace negocio {
class componentes <<entidad>> {
    +id : int
    -descripcion : str
}
class medicamento <<entidad>> {
    +id : int
    -descripcion : str
} 
class inventario <<entidad>> {
    +id : int

}
'relaciones
componentes "1..*" <.. "1" medicamento : depende de 



} 

note bottom of negocio.componentes
    componentes genericos
    de medicamentos.
    (mejora de busqueda)
end note
note bottom of negocio.medicamento
    clase de producto
    principal
end note

@enduml