@startuml uscase1
title
    caso de uso general (UCgeneral)
    **sistema de Farmacia**
end title
header
    vision global de sistema
end header
!include https://raw.githubusercontent.com/vonbeitthia/FarmaciaUML/main/skin/blue.plantuml
scale 6/3 
actor A10UsuarioAnonimo
actor A12UsuarioRegistrado 
rectangle "sistema" {
    'CRUD 
    usecase USC12AgregarMedicamento
    usecase USC10BuscarMedicamento
    usecase USC14ModificarMedicamento
    usecase USC16EliminarMedicamento
}
A10UsuarioAnonimo -- USC10BuscarMedicamento 
A12UsuarioRegistrado -u- USC10BuscarMedicamento <<token>>
A12UsuarioRegistrado -u- USC12AgregarMedicamento <<token>>
A12UsuarioRegistrado -u- USC14ModificarMedicamento <<token>>
A12UsuarioRegistrado -u- USC16EliminarMedicamento <<token>>
note right of A12UsuarioRegistrado
    el usuario registrado requiere
    autenticacion en el sistema
end note
@enduml